<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:Blocks="http://www.eclipse.org/papyrus/0.7.0/SysML/Blocks" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML">
  <uml:Model name="fsl0">
    <packageImport importedPackage="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#_0"/>
    <packagedElement xsi:type="uml:Package" name="acs">
      <packagedElement xsi:type="uml:Class" name="Building"/>
      <packagedElement xsi:type="uml:Class" name="Person">
        <ownedRule name="Inv_7a0bfa16" constrainedElement="uml:Property example/02-fsl0.sysml.ecore#/0/acs/Person/current">
          <specification xsi:type="uml:OpaqueExpression">
            <body>self.authorized->asSet()->includes(self.current)</body>
            <language>OCL</language>
          </specification>
        </ownedRule>
        <ownedAttribute name="authorized" type="uml:Class example/02-fsl0.sysml.ecore#/0/acs/Building">
          <lowerValue xsi:type="uml:LiteralInteger"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="*"/>
        </ownedAttribute>
        <ownedAttribute name="current" type="uml:Class example/02-fsl0.sysml.ecore#/0/acs/Building">
          <lowerValue xsi:type="uml:LiteralInteger" value="1"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="1"/>
        </ownedAttribute>
        <ownedOperation name="pass" postcondition="example/02-fsl0.sysml.ecore#/0/acs/Person/pass/Post_a3bdce17"
            precondition="example/02-fsl0.sysml.ecore#/0/acs/Person/pass/Pre_62657c7e">
          <ownedRule name="Pre_62657c7e" constrainedElement="uml:Operation example/02-fsl0.sysml.ecore#/0/acs/Person/pass">
            <specification xsi:type="uml:OpaqueExpression">
              <body> current &lt;> b
      </body>
              <language>OCL</language>
            </specification>
          </ownedRule>
          <ownedRule name="Post_a3bdce17" constrainedElement="uml:Operation example/02-fsl0.sysml.ecore#/0/acs/Person/pass">
            <specification xsi:type="uml:OpaqueExpression">
              <body>current = b</body>
              <language>OCL</language>
            </specification>
          </ownedRule>
          <ownedParameter name="b" type="uml:Class example/02-fsl0.sysml.ecore#/0/acs/Building"/>
        </ownedOperation>
      </packagedElement>
    </packagedElement>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_TZ_nULU5EduiKqCzJMWbGw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#/"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_fSw28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//blocks"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_rpx28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//portandflows"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_OOJC4LX8EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//requirements"/>
    </profileApplication>
  </uml:Model>
  <Blocks:Block base_Class="example/02-fsl0.sysml.ecore#/0/acs/Building"/>
  <Blocks:Block base_Class="example/02-fsl0.sysml.ecore#/0/acs/Person"/>
</xmi:XMI>
