<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:Blocks="http://www.eclipse.org/papyrus/0.7.0/SysML/Blocks" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML">
  <uml:Model name="fsl2">
    <packageImport importedPackage="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#_0"/>
    <packagedElement xsi:type="uml:Package" name="acs">
      <packagedElement xsi:type="uml:Class" name="Building">
        <ownedAttribute name="building" type="uml:Class example/04-fsl2.sysml.ecore#/0/acs/Building"
            association="example/04-fsl2.sysml.ecore#/0/A_building_gate">
          <lowerValue xsi:type="uml:LiteralInteger"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="*"/>
        </ownedAttribute>
        <ownedAttribute name="gate" type="uml:Class example/04-fsl2.sysml.ecore#/0/acs/Building"
            association="example/04-fsl2.sysml.ecore#/0/A_building_gate">
          <lowerValue xsi:type="uml:LiteralInteger"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="*"/>
        </ownedAttribute>
        <ownedOperation name="enter" postcondition="example/04-fsl2.sysml.ecore#/0/acs/Building/enter/Post_44bfeb0e"
            precondition="example/04-fsl2.sysml.ecore#/0/acs/Building/enter/Pre_d2fe5156 example/04-fsl2.sysml.ecore#/0/acs/Building/enter/P8">
          <ownedRule name="Pre_d2fe5156" constrainedElement="uml:Operation example/04-fsl2.sysml.ecore#/0/acs/Building/enter">
            <specification xsi:type="uml:OpaqueExpression">
              <body> p.aut->includes(self)
      </body>
              <language>OCL</language>
            </specification>
          </ownedRule>
          <ownedRule name="P8" constrainedElement="uml:Operation example/04-fsl2.sysml.ecore#/0/acs/Building/enter">
            <specification xsi:type="uml:OpaqueExpression">
              <body> p.sit.gate->includes(self)
      </body>
              <language>OCL</language>
            </specification>
          </ownedRule>
          <ownedRule name="Post_44bfeb0e" constrainedElement="uml:Operation example/04-fsl2.sysml.ecore#/0/acs/Building/enter">
            <specification xsi:type="uml:OpaqueExpression">
              <body>p.sit = self</body>
              <language>OCL</language>
            </specification>
          </ownedRule>
          <ownedParameter name="p" type="uml:Class example/04-fsl2.sysml.ecore#/0/acs/Person"/>
        </ownedOperation>
      </packagedElement>
      <packagedElement xsi:type="uml:Class" name="Person">
        <ownedRule name="Inv_27cbc8f6" constrainedElement="uml:Property example/04-fsl2.sysml.ecore#/0/acs/Person/sit">
          <specification xsi:type="uml:OpaqueExpression">
            <body>self.aut->asSet()->includes(self.sit)</body>
            <language>OCL</language>
          </specification>
        </ownedRule>
        <ownedAttribute name="aut" type="uml:Class example/04-fsl2.sysml.ecore#/0/acs/Building">
          <lowerValue xsi:type="uml:LiteralInteger"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="*"/>
        </ownedAttribute>
        <ownedAttribute name="sit" type="uml:Class example/04-fsl2.sysml.ecore#/0/acs/Building">
          <lowerValue xsi:type="uml:LiteralInteger" value="1"/>
          <upperValue xsi:type="uml:LiteralUnlimitedNatural" value="1"/>
        </ownedAttribute>
      </packagedElement>
    </packagedElement>
    <packagedElement xsi:type="uml:Association" name="A_building_gate" memberEnd="example/04-fsl2.sysml.ecore#/0/acs/Building/building example/04-fsl2.sysml.ecore#/0/acs/Building/gate"/>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_TZ_nULU5EduiKqCzJMWbGw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#/"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_fSw28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//blocks"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_rpx28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//portandflows"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_OOJC4LX8EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//requirements"/>
    </profileApplication>
  </uml:Model>
  <Blocks:Block base_Class="example/04-fsl2.sysml.ecore#/0/acs/Building"/>
  <Blocks:Block base_Class="example/04-fsl2.sysml.ecore#/0/acs/Person"/>
</xmi:XMI>
