<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:Requirements="http://www.eclipse.org/papyrus/0.7.0/SysML/Requirements" xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML">
  <uml:Model name="isl_0">
    <packageImport importedPackage="pathmap://UML_LIBRARIES/UMLPrimitiveTypes.library.uml#_0"/>
    <packagedElement xsi:type="uml:Package" name="acs">
      <packagedElement xsi:type="uml:Class" name="P1"/>
    </packagedElement>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_TZ_nULU5EduiKqCzJMWbGw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#/"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_fSw28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//blocks"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_rpx28LX7EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//portandflows"/>
    </profileApplication>
    <profileApplication appliedProfile="pathmap://SysML_PROFILES/SysML.profile.uml#_OOJC4LX8EduFmqQsrNB9lw">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML" references="http://www.eclipse.org/papyrus/0.7.0/SysML#//requirements"/>
    </profileApplication>
  </uml:Model>
  <Requirements:Requirement text="Das hier ist ein Test. es ist ganz gut denke ich."
      id="P1" base_Class="example.sysml.ecore#/0/acs/P1"/>
</xmi:XMI>
